eclipse-store/store

.github/workflows/maven_release.yml
pom.xml

prepare script for release

---

docs/modules/storage/pages/configuration/properties.adoc
docs/modules/storage/pages/root-instances.adoc

The continuation operator ("+") is not valid at the beginning of a line (but rather at the end), and also not necessary in all fixed cases here. Therefore the plus character was rendered verbatim.

Fix wrong markdown

---

.github/workflows/maven_deploy_snapshot_dev.yml

Description:
This pull request introduces several updates to the `.github/workflows/maven_deploy_snapshot_dev.yml` GitHub Actions workflow.
Changes include:
1. The workflow now runs on push events for all branches except `main` and branches that match the pattern `release/**`.
2. The `prepareSuffix` function has been updated to generate a suffix based on the branch name. This suffix is then stored in an environment variable for later use.
3. The project version is updated before the Maven build. The new version is formed by appending the suffix to the current version (without the `-SNAPSHOT` part) and then appending `-SNAPSHOT` again.
4. The workflow now includes a step to build and deploy the `integrations/spring-boot3` module with Java 17.
These changes aim to improve the automation of …

Update GitHub Actions Workflow for Maven Deploy Snapshot

---

docs/modules/misc/pages/integrations/cdi.adoc
docs/modules/misc/pages/integrations/spring-boot.adoc
integrations/spring-boot3/src/main/java/module-info.java
integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/DefaultEclipseStoreConfiguration.java
integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/configuration/EclipseStoreProperties.java
integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/converter/EclipseStoreConfigConverter.java
integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/suppliers/EmbeddedStorageFoundationSupplier.java
integrations/spring-boot3/src/test/java/test/eclipse/store/integrations/spring/boot/DisableStorageAutoCreateTest.java
integrations/spring-boot3/src/test/resources/application-storage-create-disable.properties

Change supplier to own type, to prevent conflicts in Spring Configuration
+ remove Component annotation from the class, which is later as a bean define. 
+ add configuration to disable auto create of default foundation or storage.

Improve Spring Integration, supplier, autocreation

---

pom.xml
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageFileManager.java

This PR addresses a potential IO Error.
The java.nio.channels.FileChannel methods transferTo(long, long, WritableByteChannel) and transferFrom(ReadableByteChannel, long, long) may not write all requested bytes in one method call therefore we need to loop them until all requested data is transferred.
The missing loop may be the cause for exceptions like
```
StorageExceptionIoWriting: Physical length 3047424 of current head file 146 is not equal its expected length of 3047612
```
as documented in #95 and mentioned in #210.
The PR is related to a PR in the Eclipse Serializer project.

Xio transfer rework

---

afs/aws/aws/src/main/java/org/eclipse/store/afs/aws/types/AwsFileSystemCreator.java
afs/aws/dynamodb/src/main/java/org/eclipse/store/afs/aws/dynamodb/types/DynamoDbFileSystemCreator.java
afs/aws/s3/src/main/java/org/eclipse/store/afs/aws/s3/types/S3FileSystemCreator.java
afs/azure/storage/src/main/java/org/eclipse/store/afs/azure/storage/types/AzureStorageFileSystemCreator.java
afs/googlecloud/firestore/src/main/java/org/eclipse/store/afs/googlecloud/firestore/types/GoogleCloudFirestoreFileSystemCreator.java
afs/kafka/src/main/java/org/eclipse/store/afs/kafka/types/KafkaFileSystemCreator.java
afs/oraclecloud/objectstorage/src/main/java/org/eclipse/store/afs/oraclecloud/objectstorage/types/OracleCloudObjectStorageFileSystemCreator.java
afs/redis/src/main/java/org/eclipse/store/afs/redis/types/RedisFileSystemCreator.java
afs/sql/src/main/java/org/eclipse/store/afs/sql/types/SqlFileSystemCreator.java
afs/sql/src/main/java/org/eclipse/store/afs/sql/types/SqlFileSystemCreatorHana.java
afs/sql/src/main/java/org/eclipse/store/afs/sql/types/SqlFileSystemCreatorMariaDb.java
afs/sql/src/main/java/org/eclipse/store/afs/sql/types/SqlFileSystemCreatorOracle.java
afs/sql/src/main/java/org/eclipse/store/afs/sql/types/SqlFileSystemCreatorPostgres.java
afs/sql/src/main/java/org/eclipse/store/afs/sql/types/SqlFileSystemCreatorSqlite.java
docs/modules/storage/pages/storage-targets/blob-stores/aws-dynamodb.adoc
docs/modules/storage/pages/storage-targets/blob-stores/aws-s3.adoc
docs/modules/storage/pages/storage-targets/blob-stores/azure-storage.adoc
docs/modules/storage/pages/storage-targets/blob-stores/google-cloud-firestore.adoc
docs/modules/storage/pages/storage-targets/blob-stores/kafka.adoc
docs/modules/storage/pages/storage-targets/blob-stores/oracle-cloud-object-storage.adoc
docs/modules/storage/pages/storage-targets/blob-stores/redis.adoc
docs/modules/storage/pages/storage-targets/sql-databases/mariadb.adoc
docs/modules/storage/pages/storage-targets/sql-databases/oracle.adoc
docs/modules/storage/pages/storage-targets/sql-databases/postgresql.adoc
docs/modules/storage/pages/storage-targets/sql-databases/sqlite.adoc
integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/configuration/EclipseStoreProperties.java
integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/configuration/StorageFilesystem.java
integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/converter/ConfigKeys.java
integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/converter/EclipseStoreConfigConverter.java
storage/embedded-configuration/src/main/java/org/eclipse/store/storage/embedded/configuration/types/EmbeddedStorageFoundationCreatorConfigurationBased.java

Add a property to enforce a certain file system provider to add checks like missing dependencies. This should prevent the accidental creation of the wrong provider.
`storage-filesystem.target=$provider`
`backup-filesystem.target=$provider`

Add file system target property

---

examples/extension-wrapper/src/main/java/org/eclipse/store/examples/extensionwrapper/PersistenceStorerWrapper.java
integrations/cdi4/src/main/java/org/eclipse/store/integrations/cdi/types/config/StorageManagerProxy.java
storage/embedded/src/main/java/org/eclipse/store/storage/embedded/types/EmbeddedStorageManager.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageConnection.java

UsageMarkable concept: To prevent Lazy references from being cleared despite having unstored changes, they can now be marked for being used for certain instances. A lazy reference can only get cleared if it has 0 usage marks.
See https://github.com/eclipse-serializer/serializer/pull/143

Storer enhancements

---

docs/modules/storage/pages/addendum/specialized-type-handlers.adoc

This pull request includes an update to the documentation in `docs/modules/storage/pages/addendum/specialized-type-handlers.adoc` to include instructions for using a new serializer foundation with JDK 17 type handlers.
Documentation update:
* [`docs/modules/storage/pages/addendum/specialized-type-handlers.adoc`](diffhunk://#diff-866045d705a4203fbc90906166e8bd8c8f804990ba5bedcf35c6b719c0b14fd0R134-R140): Added instructions for using `SerializerFoundation` with `BinaryHandlersJDK17` to register JDK 17 type handlers.

Docu:  add JDK17 Handlers to serializer foundation

---

docs/modules/storage/pages/loading-data/lazy-loading/clearing-lazy-references.adoc

This pull request includes a minor change to the `docs/modules/storage/pages/loading-data/lazy-loading/clearing-lazy-references.adoc` file. The change corrects the syntax of the `LazyReferenceManager.set` method call by adding an extra closing parenthesis.
* [`docs/modules/storage/pages/loading-data/lazy-loading/clearing-lazy-references.adoc`](diffhunk://#diff-0db7c1d0a5e6c0b2bb0c97441b857470a81d5eec6e99b39f4d9167d467decbceL36-R36): Corrected the syntax of the `LazyReferenceManager.set` method call by adding an extra closing parenthesis.

fix docu (brakets in code)

---

integrations/spring-boot3/src/test/java/test/eclipse/store/integrations/spring/boot/LockAspectTest.java

This pull request includes a new test class to verify the existence of the `LockAspect` bean in the Spring Boot application context.
Addition of a new test class:
* [`integrations/spring-boot3/src/test/java/test/eclipse/store/integrations/spring/boot/LockAspectTest.java`](diffhunk://#diff-720f1726fc5c9382e5bbde32ea4df10747e119b8c4e6ee01e2904429068fd5ffR1-R26): Added a new test class `LockAspectTest` to check if the `LockAspect` bean is present in the application context. This includes importing necessary dependencies, setting up the test context, and writing a test method `isLockAspectBeanExists` to assert the presence of the `LockAspect` bean.

add test for LockAspect bean exists.

---

afs/redis/pom.xml

This pull request includes an update to the `afs/redis/pom.xml` file to upgrade the version of the `lettuce-core` dependency.
Dependency update:
* [`afs/redis/pom.xml`](diffhunk://#diff-da02e9170a0f4e51eed2142342940ec3aa5d778678849b34932c1f866349d83eL36-R36): Upgraded `lettuce-core` from version `6.4.0.RELEASE` to `6.5.2.RELEASE`.

fix: resolve redit vulnerability by updating dependency versions

---

afs/oraclecloud/pom.xml

This pull request includes an update to the Oracle Cloud SDK dependency version in the `afs/oraclecloud/pom.xml` file. The version has been upgraded from `3.44.4` to `3.57.1`.
Dependency update:
* [`afs/oraclecloud/pom.xml`](diffhunk://#diff-f8a02ff18fea4f685deab511a3890bedb0fdb619992dea79fe172013e84e01c3L32-R32): Updated the `oci-java-sdk-bom` dependency version from `3.44.4` to `3.57.1` to ensure the latest features and fixes are included.

update OCI to 3.57.1

---

.github/workflows/maven_release.yml

This pull request includes changes to the Maven release workflow configuration in the `.github/workflows/maven_release.yml` file. The changes focus on streamlining the build and deploy steps for Java 17.
Key changes:
* Removed the separate build steps for Java 17, consolidating them into the deploy step.
* Updated the deploy step to include the `production` profile for all modules.

chore: update Maven deployment commands to include production profile

---

.github/workflows/maven_deploy_snapshot.yml
.github/workflows/maven_deploy_snapshot_dev.yml

This pull request includes changes to the Maven deployment workflows to streamline the build and deployment process. The most important changes involve removing redundant build steps and ensuring that all deployments use the production profile.
Improvements to Maven deployment workflows:
* [`.github/workflows/maven_deploy_snapshot.yml`](diffhunk://#diff-90e483e757fc53fb36f9124261704451c10f53e476a7e4b1580f52c8a4ea20c0L52-R55): Removed redundant build steps and added the `production` profile to the deployment commands.
* [`.github/workflows/maven_deploy_snapshot_dev.yml`](diffhunk://#diff-1bd6a250b0687be2e84d36516305bd217ea856858e767d20d34c03c645973e98L114-R117): Removed redundant build steps and added the `production` profile to the deployment commands.

chore: update Maven deployment commands to include production profile - dev build

---

examples/spring-boot3-advanced/pom.xml
examples/spring-boot3-simple/pom.xml
integrations/spring-boot3-console/pom.xml
integrations/spring-boot3/pom.xml

This pull request updates the Spring Boot version across multiple `pom.xml` files to ensure consistency and take advantage of the latest features and fixes provided in version 3.4.5.
Version updates:
* [`examples/spring-boot3-advanced/pom.xml`](diffhunk://#diff-3d878e0c0b66f01e7bdea2254ba1440c7b658e35a8d8ad4141e0d1165899f983L21-R21): Updated `<spring.boot.version>` from `3.2.2` to `3.4.5`.
* [`examples/spring-boot3-simple/pom.xml`](diffhunk://#diff-804ca3fe8bab5d865dba840ea1ea85d471729c6838b8e6de0daa171d2a127b7cL21-R21): Updated `<spring.boot.version>` from `3.2.2` to `3.4.5`.
* [`integrations/spring-boot3-console/pom.xml`](diffhunk://#diff-edb745cc289cf9d279366e508f6468114761d00e2e79f7ec98ef6d977ef109cfL19-R19): Updated `<org.springframework.boot.version>` from `3.2.0` to `3.4.5`.
* …

chore: update Spring Boot version to 3.4.5 in pom.xml

---

storage/rest/service-sparkjava/pom.xml

This pull request updates the `jetty.version` property in the `pom.xml` file to a newer version, ensuring compatibility with the latest Jetty release.
Dependency update:
* [`storage/rest/service-sparkjava/pom.xml`](diffhunk://#diff-69e75cb09be38aae2eb87e36b96e5748ec6e414870959bb31e809da74dbefb0aL24-R24): Updated `jetty.version` from `9.4.56.v20240826` to `9.4.57.v20241219` to incorporate the latest fixes and improvements.

chore: update jetty.version to 9.4.57.v20241219 in pom.xml

---

.github/workflows/maven_build.yml
.github/workflows/maven_build_win.yml
.github/workflows/maven_converter.yml
.github/workflows/maven_deploy_snapshot.yml
.github/workflows/maven_deploy_snapshot_dev.yml
integrations/itest/pom.xml
integrations/pom.xml
integrations/spring-boot3-console/pom.xml
integrations/spring-boot3/pom.xml
pom.xml
storage/rest/client-app-standalone-assembly/pom.xml
storage/rest/client-app/pom.xml
storage/rest/pom.xml
storage/rest/service-springboot/pom.xml

This pull request updates the Maven build configurations and project files to standardize Java version usage across workflows and modules. The most significant changes involve removing Java 11 configurations, consolidating builds to Java 17, and simplifying Maven profiles and properties.
* [`.github/workflows/maven_build.yml`](diffhunk://#diff-5e9df5c7ba9a0e12d454053f62cec530d95c52e2dc4a4f1e6755b6499686d764L17-L28): Removed Java 11 build steps, retaining only Java 17 build configurations.
* [`.github/workflows/maven_build_win.yml`](diffhunk://#diff-e77b56b9896f79686ebc79a8aa2f9a3504f3a42badbb6f53e667642a68fa6259L17-L28): Similar to the Ubuntu workflow, removed Java 11 build steps while keeping Java 17 configurations. [[1]](diffhunk://#diff-e77b56b9896f79686ebc79a8aa2f9a3504f3a42badbb6f53e6 …

chore: update build configurations to use JDK 17

---

pom.xml

This pull request updates the minimum required Java version for the project. The `maven.java.version.minimum` property in the `pom.xml` file has been updated from Java 11 to Java 17.
- [`pom.xml`](diffhunk://#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L43-R43): Updated the `maven.java.version.minimum` property to require Java 17 instead of Java 11.

chore: update minimum Java version in pom.xml to 17

---

afs/googlecloud/firestore/src/main/java/org/eclipse/store/afs/googlecloud/firestore/types/GoogleCloudFirestoreFileSystemCreator.java
integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/converter/ConfigKeys.java
integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/converter/EclipseStoreConfigConverter.java
integrations/spring-boot3/src/test/java/org/eclipse/store/integrations/spring/boot/types/converter/EclipseStoreConfigConverterTest.java

This pull request introduces support for Google Cloud Firestore configuration in the project, including updates to the configuration keys, conversion logic, and associated tests. The most important changes include adding Firestore-specific configuration keys, implementing logic to handle Firestore properties, and adding a test to validate the new functionality.
* Added Firestore-specific configuration keys to the `ConfigKeys` enum, enabling support for properties like `database-id`, `emulator-host`, `host`, `project-id`, `quota-project-id`, and `credentials.type` (`integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/converter/ConfigKeys.java`).
* Updated the `EclipseStoreConfigConverter` to handle Firestore configuration by adding a …

427 no sub keys for googlecloudfirestore for googlecloudfirestorefilesystemcreator found

---

examples/gigamap/src/main/java/org/eclipse/store/examples/gigamap/Address.java
examples/gigamap/src/main/java/org/eclipse/store/examples/gigamap/BasicExample.java
examples/gigamap/src/main/java/org/eclipse/store/examples/gigamap/Interest.java
examples/gigamap/src/main/java/org/eclipse/store/examples/gigamap/Person.java
examples/gigamap/src/main/java/org/eclipse/store/examples/gigamap/PersonIndices.java
examples/gigamap/src/main/java/org/eclipse/store/examples/gigamap/RandomGenerator.java

This pull request adds licensing information to several files in the `examples/gigamap` package. The changes involve including a standard header that specifies the Eclipse Public License 2.0 for each file.
* Added a license header specifying the Eclipse Public License 2.0 to the following files:
- `Address.java`
- `BasicExample.java`
- `Interest.java`
- `Person.java`
- `PersonIndices.java`
- `RandomGenerator.java`

chore: add license headers to Java files

---

gigamap/gigamap/src/test/java/org/eclipse/store/gigamap/crud/RemovalAllMemoryTest.java
gigamap/gigamap/src/test/java/org/eclipse/store/gigamap/crud/SetTest.java
gigamap/gigamap/src/test/java/org/eclipse/store/gigamap/experimental/ThreadCountProviderTest.java
gigamap/gigamap/src/test/java/org/eclipse/store/gigamap/indexer/IterationThreadProviderTest.java
gigamap/gigamap/src/test/java/org/eclipse/store/gigamap/indexer/binary/BinaryUUIDIndexTest.java
gigamap/gigamap/src/test/java/org/eclipse/store/gigamap/indexer/edge/QueryVariableTests.java
gigamap/gigamap/src/test/java/org/eclipse/store/gigamap/indexer/enumeration/StoreEnumInsideTest.java
gigamap/gigamap/src/test/java/org/eclipse/store/gigamap/indexer/enumeration/StoreEnumTest.java
gigamap/gigamap/src/test/java/org/eclipse/store/gigamap/query/NumberSearchTest.java
gigamap/gigamap/src/test/java/org/eclipse/store/gigamap/restart/AddTest.java
gigamap/gigamap/src/test/java/org/eclipse/store/gigamap/restart/update/SmallEVTest.java

This pull request primarily updates tests in the `gigamap` module by cleaning up debugging output and improving test assertions, as well as updating references to issue trackers. It also adds a new test for storing enums inside objects. These changes help make the test suite cleaner and more maintainable.
**Test assertion improvements:**
* Enhanced assertions in `StoreEnumTest.java` to check for correct enum list contents after loading from storage, replacing print statements with `Assertions.assertIterableEquals`. [[1]](diffhunk://#diff-5d7d77145e6afb8e00623074f0f72cfe1ac463f1b5724b23a904814ecd7bb242L50-R54) [[2]](diffhunk://#diff-5d7d77145e6afb8e00623074f0f72cfe1ac463f1b5724b23a904814ecd7bb242L68-R73)
* Added a new test `StoreEnumInsideTest.java` to verify storing enums inside nested …

chore: remove println statements from test files

---

.github/workflows/generate-maven-sbom.yml
README.md
pom.xml

This PR aims to bootstrap the EF Security Team initiative of generating and publishing SBOMs for project releases, with the goal of enhancing software supply chain security.
To not interfere with your existing release processes, this PR proposes a new workflow to generate and publish SBOMs autonomously, following GitHub releases of the **store** product. The workflow respects the existing SBOM plugin configuration in `pom.xml`, which is updated to use the latest SBOM schema version.[^1]
In addition to the release event, the workflow can be triggered manually to test SBOM generation, or to generate SBOMs for past releases.
Following a workflow run, the EF self-service system automatically publishes the SBOM on our DependencyTrack [instance](https://sbom.eclipse.org/), under the **Eclipse …

chore: add sbom generation and upload workflow

---

examples/spring-boot3-advanced/pom.xml
examples/spring-boot3-simple/pom.xml
integrations/spring-boot3-console/pom.xml
integrations/spring-boot3/pom.xml
storage/rest/client-app/pom.xml

This pull request updates several Maven project files to use newer versions of Spring Boot and related dependencies, ensuring all modules are aligned with the latest stable releases. The changes also include upgrades to the Maven Compiler Plugin and the Springdoc OpenAPI dependency for improved compatibility and features.
**Dependency version updates:**
* Upgraded `spring.boot.version` (or `org.springframework.boot.version`) from `3.4.5` or `3.2.0` to `3.5.6` in `examples/spring-boot3-advanced/pom.xml`, `examples/spring-boot3-simple/pom.xml`, `integrations/spring-boot3-console/pom.xml`, `integrations/spring-boot3/pom.xml`, and `storage/rest/client-app/pom.xml` for consistent use of the latest Spring Boot release. [[1]](diffhunk://#diff-3d878e0c0b66f01e7bdea2254ba1440c7b658e35a8d8ad4141e0d1 …

chore: update Spring Boot version to 3.5.6
