afs/googlecloud/firestore/src/main/java/org/eclipse/store/afs/googlecloud/firestore/types/GoogleCloudFirestoreConnector.java
afs/googlecloud/firestore/src/main/java/org/eclipse/store/afs/googlecloud/firestore/types/GoogleCloudFirestoreFileSystemCreator.java
afs/googlecloud/firestore/src/main/java/org/eclipse/store/afs/googlecloud/firestore/types/GoogleCloudFirestorePathValidator.java
afs/googlecloud/pom.xml
storage/rest/service-sparkjava/README.md

pom.xml used old artifactId and old imports where used.

Fix artifactId and fix imports

---

pom.xml

remove javadoc-aggregate profile

remove javadoc-aggregate profile

---

docs/modules/storage/pages/configuration/backup/continuous-backup.adoc

Added external config example howto use different file systems for storage and continuous backup

update backup documentation

---

docs/modules/ROOT/nav.adoc
docs/modules/storage/pages/configuration/readonly.adoc
docs/modules/storage/pages/configuration/storage-files-and-directories.adoc
docs/modules/storage/pages/configuration/using-channels.adoc

fixing docu #74

---

docs/modules/storage/pages/configuration/housekeeping.adoc
docs/modules/storage/pages/configuration/properties.adoc
storage/embedded-configuration/src/main/java/org/eclipse/store/storage/embedded/configuration/types/EmbeddedStorageConfigurationBuilder.java
storage/embedded-configuration/src/main/java/org/eclipse/store/storage/embedded/configuration/types/EmbeddedStorageConfigurationPropertyNames.java
storage/embedded-configuration/src/main/java/org/eclipse/store/storage/embedded/configuration/types/EmbeddedStorageFoundationCreatorConfigurationBased.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageEventLogger.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageFoundation.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageHousekeepingController.java

migrating https://github.com/microstream-one/microstream/pull/641

migration of adaptive housekeeping feature

---

storage/storage/src/main/java/org/eclipse/store/storage/types/StorageChannelTaskInitialize.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageFoundation.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageSystem.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageTimestampProvider.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageTransactionsAnalysis.java

see https://github.com/microstream-one/microstream/pull/643

Migration of feature time stamp provider monotonic (#643)

---

docs/modules/storage/pages/configuration/properties.adoc
storage/embedded-configuration/src/main/java/org/eclipse/store/storage/embedded/configuration/types/EmbeddedStorageConfigurationBuilder.java
storage/embedded-configuration/src/main/java/org/eclipse/store/storage/embedded/configuration/types/EmbeddedStorageConfigurationPropertyNames.java
storage/embedded-configuration/src/main/java/org/eclipse/store/storage/embedded/configuration/types/EmbeddedStorageFoundationCreatorConfigurationBased.java
storage/embedded/src/main/java/org/eclipse/store/storage/embedded/types/EmbeddedStorageManager.java
storage/storage/src/main/java/org/eclipse/store/storage/types/Storage.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageBackupItemQueue.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageChannel.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageConnection.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageDataFileEvaluator.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageFileManager.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageHousekeepingBroker.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageHousekeepingExecutor.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageRequestAcceptor.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageRequestTaskCreator.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageRequestTaskTransactionsLogCleanup.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageTaskBroker.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageTransactionsFileCleaner.java

see https://github.com/microstream-one/microstream/pull/645

Migration of feature "transaction file housekeeping" #645

---

docs/modules/intro/pages/system-requirements.adoc
docs/modules/storage/pages/storage-targets/blob-stores/azure-storage.adoc
docs/modules/storage/pages/storage-targets/blob-stores/google-cloud-firestore.adoc

fixes from release/1x

---

.github/workflows/maven_build.yml
.github/workflows/maven_converter.yml
examples/layered-entities/pom.xml
examples/spring-boot3-simple/pom.xml
integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/configuration/EclipseStoreProperties.java
pom.xml
storage/embedded-tools/storage-converter/pom.xml

Update plugins + build script improves

Update Maven Plugins

---

docs/modules/storage/pages/rest-interface/setup.adoc

bases on https://github.com/eclipse-store/store/pull/98

fix import

---

cache/hibernate/src/main/java/org/eclipse/store/cache/hibernate/types/CacheRegionFactory.java

SecondLevelCacheLogger singleton was renamed in Hibernate 6. So, we have to use reflection to acquire the logger since there is no provider of any sort.

Add multi-version hibernate logging

---

docs/modules/misc/pages/integrations/spring-boot.adoc

Spring docu fix - autowired into method param

---

examples/wildfly-cdi4/pom.xml
integrations/cdi4/pom.xml

PR was not actual, fix versions

fix versions

---

docs/modules/storage/pages/configuration/backup/continuous-backup.adoc

Typo in continuous-backup.adoc

---

integrations/spring-boot3/src/test/java/test/eclipse/store/integrations/spring/boot/advance/AdvanceRestartRoot.java
integrations/spring-boot3/src/test/java/test/eclipse/store/integrations/spring/boot/advance/AdvanceRestartTest.java
integrations/spring-boot3/src/test/resources/application-advance-restart-test.properties

Add advance restart spring boot test

Add advance restart spring boot test

---

docs/modules/misc/pages/integrations/spring-boot.adoc

Add dependency information into Spring boot Extension Documentation

Add dependency information into Spring boot Extension Documentation

---

docs/modules/misc/pages/layered-entities/configuration.adoc
docs/modules/storage/pages/storing-data/deep-copy.adoc

fixing docu issues issue 207 and 208

---

afs/aws/s3/src/main/java/org/eclipse/store/afs/aws/s3/types/S3Connector.java

See https://github.com/eclipse-store/store/discussions/188#discussioncomment-8948050

Adjust code to ensure Minio compatibility

---

docs/modules/misc/pages/integrations/spring-boot.adoc

merge from main

---

examples/extension-wrapper/src/main/java/org/eclipse/store/examples/extensionwrapper/PersistenceStorerWrapper.java

Ensure compatibility to https://github.com/eclipse-serializer/serializer/commit/216804167484f0c979d2d742d9c97cf17194df02

Commit listener registration

---

docs/modules/ROOT/nav.adoc
docs/modules/storage/pages/addendum/tools.adoc
storage/embedded-tools/storage-converter/README.md

Added a README.md for the storage converter tool
Added docs for converter and migration tools.

Tooling Documentation

---

afs/aws/aws/src/main/java/module-info.java
afs/aws/dynamodb/src/main/java/org/eclipse/store/afs/aws/dynamodb/types/DynamoDbFileSystemCreator.java
afs/aws/pom.xml
afs/aws/s3/src/main/java/org/eclipse/store/afs/aws/s3/types/S3Connector.java
afs/aws/s3/src/main/java/org/eclipse/store/afs/aws/s3/types/S3FileSystemCreator.java
afs/azure/storage/src/main/java/org/eclipse/store/afs/azure/storage/types/AzureStorageFileSystemCreator.java
afs/googlecloud/firestore/src/main/java/org/eclipse/store/afs/googlecloud/firestore/types/GoogleCloudFirestoreFileSystemCreator.java
afs/kafka/src/main/java/org/eclipse/store/afs/kafka/types/KafkaFileSystemCreator.java
afs/nio/src/main/java/org/eclipse/store/afs/nio/types/NioFileSystem.java
afs/oraclecloud/objectstorage/src/main/java/org/eclipse/store/afs/oraclecloud/objectstorage/types/OracleCloudObjectStorageFileSystemCreator.java
afs/redis/src/main/java/org/eclipse/store/afs/redis/types/RedisFileSystemCreator.java
afs/sql/src/main/java/org/eclipse/store/afs/sql/types/SqlFileSystemCreator.java
docs/modules/storage/pages/storage-targets/blob-stores/aws-dynamodb.adoc
docs/modules/storage/pages/storage-targets/blob-stores/aws-s3.adoc
docs/modules/storage/pages/storage-targets/index.adoc
integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/configuration/aws/AbstractAwsProperties.java
integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/configuration/aws/S3.java
integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/converter/ConfigKeys.java
integrations/spring-boot3/src/main/java/org/eclipse/store/integrations/spring/boot/types/converter/EclipseStoreConfigConverter.java
storage/embedded-configuration/src/main/java/org/eclipse/store/storage/embedded/configuration/types/EmbeddedStorageFoundationCreatorConfigurationBased.java

Add support for directory buckets (#224).
Fix for #234.
Fix in configuration layer, which solves #233.
Documentation update.

S3 enhancements

---

pom.xml

update plugins, always check new snapshot

update plugins, always check new snapshot

---

docs/modules/misc/pages/integrations/spring-boot.adoc

Add Spring docu about dev tools.

add spring docu about Spring dev tools.

---

examples/spring-boot3-simple/pom.xml
examples/spring-boot3-simple/readme.md
examples/spring-boot3-simple/src/main/resources/application-awss3.properties

Add profile to maven and spring to launch Spring example with AWS S3 + readme

add profile to example for AWS S3

---

examples/spring-boot3-advanced/src/main/java/org/microstream/spring/boot/example/advanced/storage/JokesStorageImpl.java
examples/spring-boot3-simple/src/main/java/org/microstream/spring/boot/example/simple/storage/JokesStorageImpl.java
examples/spring-boot3-simple/src/main/resources/logback.xml

https://github.com/eclipse-store/store/discussions/266
One bug has been found in our examples. 
Fix. 
Please merge without me.

fix bug in spring examples

---

storage/storage/src/main/java/org/eclipse/store/storage/types/StorageFile.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageLiveDataFile.java

fixing issue #264

---

afs/aws/s3/src/main/java/org/eclipse/store/afs/aws/s3/types/S3Connector.java
afs/blobstore/src/main/java/org/eclipse/store/afs/blobstore/types/BlobStoreConnector.java

Ensure correct inventorisation of S3 directories

---

storage/storage/src/main/java/org/eclipse/store/storage/types/StorageDataConverterTypeBinaryToCsv.java

Add constructor methods for CSV converter

---

afs/aws/pom.xml
afs/azure/pom.xml
afs/googlecloud/pom.xml
afs/kafka/pom.xml
afs/oraclecloud/pom.xml
afs/redis/pom.xml

The goal of this PR is dependency update of our AFS connectors.

afs update

---

storage/embedded-configuration/src/main/java/org/eclipse/store/storage/embedded/configuration/types/EmbeddedStorageFoundationCreatorConfigurationBased.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageEntityMarkMonitor.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageHousekeepingController.java

The controller doesn't increase the housekeeping's time budget when the GC is idle.

Fix adaptive housekeeping

---

storage/storage/src/main/java/org/eclipse/store/storage/types/StorageFile.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageLockFileManager.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageLockFileManagerThreadProvider.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageSystem.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageThreadProvider.java

Ensure lock file exists

---

storage/storage/src/main/java/org/eclipse/store/storage/types/StorageFoundation.java

added platform dependent MonitoringManager initialization

fixing android issues #325 storage part

---

examples/extension-wrapper/src/main/java/org/eclipse/store/examples/extensionwrapper/PersistenceStorerWrapper.java

Implementation of https://github.com/eclipse-store/store/issues/139
storage related part

added API that allows collecting Objects that are going to be persisted

---

docs/modules/storage/pages/rest-interface/index.adoc

Fixed outdated sentence in the docs about rest-api.

Updated sentence in doc about rest-api

---

storage/rest/adapter/src/main/java/org/eclipse/store/storage/restadapter/types/ViewerBinaryPersistenceManager.java
storage/rest/adapter/src/main/java/org/eclipse/store/storage/restadapter/types/ViewerBinaryTypeHandlerManager.java

depends upon https://github.com/eclipse-serializer/serializer/pull/178

added viewRoots() method

---

cache/cache/src/main/java/org/eclipse/store/cache/types/Cache.java
cache/cache/src/main/java/org/eclipse/store/cache/types/CacheConfiguration.java
cache/cache/src/main/java/org/eclipse/store/cache/types/CacheConfigurationBuilderConfigurationBased.java
cache/cache/src/main/java/org/eclipse/store/cache/types/CacheConfigurationPropertyNames.java
cache/cache/src/main/java/org/eclipse/store/cache/types/CacheEntry.java
cache/cache/src/main/java/org/eclipse/store/cache/types/CacheEvent.java
cache/cache/src/main/java/org/eclipse/store/cache/types/CacheStore.java
cache/cache/src/main/java/org/eclipse/store/cache/types/CacheTable.java
cache/cache/src/main/java/org/eclipse/store/cache/types/CachedValue.java
cache/cache/src/main/java/org/eclipse/store/cache/types/MutableCacheEntry.java

- Introduced `TableProvider` abstraction to simplify and encapsulate table management logic in `CacheStore`.
- Replaced `EmbeddedStorageManager` with `StorageManager` for better handling of storage operations.
- Updated code formatting and fixed existing warnings for improved readability and maintainability.

Refactor CacheStore and improve backend code quality

---

storage/storage/src/main/java/org/eclipse/store/storage/types/StorageActivePart.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageController.java
storage/storage/src/main/java/org/eclipse/store/storage/types/StorageSystem.java

Enhanced the documentation for `StorageSystem`, `StorageController`, and `StorageActivePart` interfaces by adding comprehensive JavaDocs. These additions aim to improve clarity on functionalities and usage within the codebase. No functional changes have been made.
Implements #401

Update storage system interfaces with detailed JavaDocs

---

docs/modules/ROOT/nav.adoc
docs/modules/storage/pages/addendum/storage-graph-analysis.adoc
docs/modules/storage/pages/addendum/troubleshooting.adoc

Create storage-analysis.adoc and troubleshooting.adoc

---

docs/modules/gigamap/pages/getting-started.adoc

3.0.0 doc fix

---

storage/storage/src/main/java/org/eclipse/store/storage/types/StorageFile.java

replaced StorageExceptionIoReading with a correct StorageExceptionIoWriting

---

gigamap/gigamap/src/main/java/org/eclipse/store/gigamap/types/SubBitmapIndexBinary.java
gigamap/gigamap/src/test/java/org/eclipse/store/gigamap/issues/GigaMap458Test.java

Patch for SubBitmapIndexBinary updates

---

docs/modules/gigamap/pages/indexing/lucene/index.adoc
docs/modules/intro/pages/changelog.adoc
docs/modules/intro/pages/installation.adoc

- Updated the migration guide.
- Fixed the group ID issue.
- Update modules
- Update GigaMap lucene docs

Documentation update
